# window height and width
WIN_WIDTH = 700
WIN_HEIGHT = 600

# define how fast obstacles and background move
SCENE_SPEED = 7
OBJ_SPEED = 17
PLAYER_VEL = 19
ITEMS_DROP_VEL = 2

PROJECTILE_VEL = 30
EXPLODING_TIME = 16

OBSTACLE_GAP = 100

PLAYER_HEALTH = 100
HEART_HEALING_RATE = 0.5

PROJECTILE_DAMAGE = 5

ENEMY_BASE_HEALTH = 500
ENEMY_MAX_HEALTH = 1000
